stages:
  - build

before_script:
  - git fetch origin --tags
  - git submodule update --init --recursive
  - mkdir ./install_dir

build-mac-amd64:
  stage: build
  tags:
    - mac-amd64
  script:
    - cmake -B build -G Xcode -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0  -DCMAKE_OSX_ARCHITECTURES="x86_64" -DENABLE_VIRTUALCAM=OFF -DCMAKE_INSTALL_PREFIX="./install_dir"
    - cmake --build build --config Release
    - cmake --install build
    - cmake --install build --component Development 
  artifacts:
    name: obs-dev
    paths:
      - ./install_dir


build-windows-amd64:
  stage: build
  tags:
    - windows
  script:
    - cmake -B build -G "Visual Studio 17"  -DCMAKE_INSTALL_PREFIX="./install_dir"
    - cmake --build build --config Release
    - cmake --install build
    - cmake --install build --component obs_libraries 
  artifacts:
    name: obs-dev
    paths:
      - ./install_dir