stages:
  - build

build-mac-amd64:
  stage: build
  tags:
    - mac-amd64
  script:
    - sudo cmake -B build -G Xcode -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0  -DCMAKE_OSX_ARCHITECTURES="x86_64" -DENABLE_VIRTUALCAM=OFF -DCMAKE_INSTALL_PREFIX="./install"
    - sudo cmake --build build --config Release
    - sudo cmake --install build
    - sudo cmake --install build --component Development 
  artifacts:
    name: libobs 
    paths:
      - ./install